### ISSUE TITLE
Support adding an offline OIDC issuer

### ISSUE THREAD

**Issue by mvladev** [gardener/oidc-webhook-authenticator#2]
**What would you like to be added**:

It should be possible to specify the JWKS in the `OpenIDConnect` resource directly:

```yaml
apiVersion: authentication.gardener.cloud/v1alpha1
kind: OpenIDConnect
metadata:
  name: my-not-reachable-oidc-idp
spec:
  issuerURL: https://somewhewre.internal
  clientID: some-key
  jwks:
    keys: f31deA9b... #the content of jwks_uri base64-encoded
    distributedClaims: true
```

In this case, the expected behavior would be to not do any OIDC discovery and directly use the `spec.offlineJWKS.keys` value instead.  The following rules apply:

- JWKS rotation should happen with updates to the `spec.offlineJWKS.keys` value.
- [distributed claims](https://openid.net/specs/openid-connect-core-1_0.html#AggregatedDistributedClaims) should be disabled by default and enabled by `spec.offlineJWKS.distributedClaims: true`.

**Why is this needed**:

Today, each OIDC IDP must be reachable from the webhook. For on-premise deployments or where network connectivity cannot be assured, manually specifying the JWKS content could be sufficient workaround without the need for complex networking setup.
