### ISSUE TITLE
Unable to authenticate the request - certificate signed by unknown authority

### ISSUE THREAD

**Issue by jianhang33** [gardener/oidc-webhook-authenticator#94]
**What happened**:
I deployed an instance of oidc-webhook-authenticator in my cluster, and when I make a request to my cluster, I saw a message in the log of oidc-webhook-authenticator

> I0128 00:43:20.035186       1 pathrecorder.go:241] oidc-webhook-authenticator: "/validate-token" satisfied by exact match 

However, in apiserver's log, I saw this

> E0128 00:43:20.037068       1 authentication.go:63] "Unable to authenticate the request" err="invalid bearer token" 

and the output of kubectl is

> error: You must be logged in to the server (Unauthorized)

The token I used to run kubectl is fresh.

I struggled to figure out what certificates to use. Self-signed certificates doesn't seem to work.

**What you expected to happen**:
authentication should pass

**How to reproduce it (as minimally and precisely as possible)**:
I used the root certificate of control plane node (/etc/kubernetes/pki/ca.crt and ca.key) to create a server certificate, and put both ca.crt and server.crt to tls.crt used by the authenticator. For webhook plugin, we used /etc/kubernetes/pki/apiserver-kubelet-client.crt and apiserver-kubelet-client.key.

**Anything else we need to know**:

**Environment**: Linux, Kubernetes

**Comment by vpnachev** [comment]
@jianhang33 can you provide us with detailed step by step instruction how to reproduce this issue?

**Comment by jianhang33** [comment]
Here is the config for webwook plugin config file named gardener-authn-webhook.yaml
```
apiVersion: v1
kind: Config
clusters:
  - name: gardener-authn-service
    cluster:
      insecure-skip-tls-verify: true
      server: https://100.89.145.84:443/validate-token
users:
  - name: api-server
    user:
      client-certificate: /etc/kubernetes/pki/apiserver-kubelet-client.crt  
      client-key: /etc/kubernetes/pki/apiserver-kubelet-client.key          
current-context: webhook-authn
contexts:
- context:
    cluster: gardener-authn-service
    user: api-server
  name: webhook-authn
```

and when the k8s cluster starts, these flags are included
```
--authentication-token-webhook-config-file=/etc/kubernetes/authn/gardener-authn-webhook.yaml
--authentication-token-webhook-cache-ttl=10s
--authentication-token-webhook-version=v1
```

After the k8s cluster is up, I did the following

1. apply config/samples/minikube-webhook-kubeconfig.yaml
2. generate a server certificate from the root certificate/key of the k8s cluster with SAM including 100.89.145.84
3. modify the file config/samples/deployment.yaml to replace the certificate/key in the secret oidc-webhook-authenticator with the server certificate/key created above and the k8s's root certificate
4. remove anything related to dex (as I use my own identity provider) in deployment.yaml
5. deploy deployment.yaml
6. deploy OpenIDConnect object for my identity provider (using jwks)
7. get a token from my identity provider, and run 'kubectl get pods --kubeconfig <kubeconfig.noUserCertificate-key> --token <token>
